server:
  port: ${APP_PORT:8080}
spring:
  application:
    name: stocks
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:60000}
  cache:
    redis:
      time-to-live: ${CACHE_EXPIRATION:60000}
info:
  app:
    name: stocks
    description: Stocks spring boot
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
  health:
    probes:
      enabled: true

feign.compression:
  request.enabled: true
  response.enabled: true

stocks:
  api-uri: ${STOCKS_API_URI:https://mfinance.com.br/api/v1/stocks}

logging:
  level:
    org:
      springframework:
        cache: TRACE

retry:
  maxAttempts: ${RETRY_MAX_ATTEMPTS:3}
  maxDelay: ${RETRY_MAX_DELAY:3000}

